all:
	docker run  -v $$PWD/src:/usr/src/app/src -v $$PWD/build:/usr/src/app/build -v $$PWD/portal.ld:/usr/src/app/portal.ld -v $$PWD/vpk:/usr/src/app/vpk -it portal64 make

image:
	docker build -t portal64 .

bash:
	docker run  -v $$PWD/src:/usr/src/app/src -v $$PWD/build:/usr/src/app/build -v $$PWD/portal.ld:/usr/src/app/portal.ld -v $$PWD/vpk:/usr/src/app/vpk -it portal64 bash

clean:
	sudo rm -rf build

