

#include "dejavusans.h"

struct FontKerning gDejaVuSansKerning[] = {
    {.amount = -1, .first = 76, .second = 84},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 76, .second = 86},
    {.amount = -1, .first = 84, .second = 111},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 76, .second = 89},
    {.amount = -1, .first = 84, .second = 114},
    {.amount = -1, .first = 84, .second = 115},
    {.amount = -1, .first = 89, .second = 111},
    {.amount = -1, .first = 84, .second = 117},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 119},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 121},
    {.amount = -1, .first = 89, .second = 117},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 97},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 99},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 101},
    {.amount = -1, .first = 89, .second = 97},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 89, .second = 101},
    {.amount = 0, .first = 0, .second = 0},
};


struct FontSymbol gDejaVuSansSymbols[] = {
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 1, .y = 10,
        .width = 1, .height = 1,
        .xoffset = 0, .yoffset = 10,
        .xadvance = 4,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 49, .y = 12,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 28, .y = 2,
        .width = 6, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 81, .y = 2,
        .width = 7, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 58, .y = 12,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 67, .y = 12,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 76, .y = 12,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 85, .y = 12,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 94, .y = 12,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 103, .y = 12,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 112, .y = 12,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 91, .y = 22,
        .width = 9, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 89, .y = 2,
        .width = 7, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 101, .y = 22,
        .width = 9, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 1, .y = 22,
        .width = 8, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 97, .y = 2,
        .width = 7, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 35, .y = 2,
        .width = 6, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 6,
    },
    {
        .x = 111, .y = 22,
        .width = 9, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 9,
    },
    {
        .x = 10, .y = 22,
        .width = 8, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 7, .y = 2,
        .width = 3, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 3,
    },
    {
        .x = 12, .y = 42,
        .width = 5, .height = 11,
        .xoffset = -1, .yoffset = 2,
        .xadvance = 3,
    },
    {
        .x = 19, .y = 22,
        .width = 8, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 105, .y = 2,
        .width = 7, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 6,
    },
    {
        .x = 1, .y = 32,
        .width = 9, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 9,
    },
    {
        .x = 28, .y = 22,
        .width = 8, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 71, .y = 32,
        .width = 10, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 9,
    },
    {
        .x = 113, .y = 2,
        .width = 7, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 1, .y = 42,
        .width = 10, .height = 10,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 9,
    },
    {
        .x = 37, .y = 22,
        .width = 8, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 46, .y = 22,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 11, .y = 32,
        .width = 9, .height = 9,
        .xoffset = -1, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 21, .y = 32,
        .width = 9, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 31, .y = 32,
        .width = 9, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 104, .y = 32,
        .width = 12, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 11,
    },
    {
        .x = 41, .y = 32,
        .width = 9, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 51, .y = 32,
        .width = 9, .height = 9,
        .xoffset = -1, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 61, .y = 32,
        .width = 9, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 8,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 1, .y = 14,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 49, .y = 1,
        .width = 7, .height = 10,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
    },
    {
        .x = 9, .y = 14,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 6,
    },
    {
        .x = 57, .y = 1,
        .width = 7, .height = 10,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
    },
    {
        .x = 55, .y = 24,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 21, .y = 1,
        .width = 6, .height = 10,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 4,
    },
    {
        .x = 24, .y = 44,
        .width = 7, .height = 9,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 65, .y = 1,
        .width = 7, .height = 10,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
    },
    {
        .x = 11, .y = 2,
        .width = 3, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 3,
    },
    {
        .x = 18, .y = 42,
        .width = 5, .height = 11,
        .xoffset = -1, .yoffset = 2,
        .xadvance = 3,
    },
    {
        .x = 73, .y = 1,
        .width = 7, .height = 10,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 6,
    },
    {
        .x = 3, .y = 1,
        .width = 3, .height = 10,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 3,
    },
    {
        .x = 82, .y = 34,
        .width = 10, .height = 7,
        .xoffset = 1, .yoffset = 4,
        .xadvance = 11,
    },
    {
        .x = 17, .y = 14,
        .width = 7, .height = 7,
        .xoffset = 1, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 64, .y = 24,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 32, .y = 44,
        .width = 7, .height = 9,
        .xoffset = 1, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 40, .y = 44,
        .width = 7, .height = 9,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 15, .y = 4,
        .width = 5, .height = 7,
        .xoffset = 1, .yoffset = 4,
        .xadvance = 5,
    },
    {
        .x = 25, .y = 14,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 6,
    },
    {
        .x = 42, .y = 2,
        .width = 6, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 4,
    },
    {
        .x = 33, .y = 14,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 73, .y = 24,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 93, .y = 34,
        .width = 10, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 9,
    },
    {
        .x = 82, .y = 24,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 48, .y = 44,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
    },
    {
        .x = 41, .y = 14,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 6,
    },
};

struct Font gDejaVuSansFont = {
    .kerning = &gDejaVuSansKerning[0],
    .symbols = &gDejaVuSansSymbols[0],
    .base = 10,
    .charHeight = 12,
    .symbolCount = 123,
    .kerningMultiplier = 1,
    .kerningMask = 0x1f,
    .maxCollisions = 0,
};

