

#include "font.h"

struct FontKerning gDejaVuSansKerning[] = {
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 97},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 99},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 101},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 121, .second = 46},
    {.amount = -1, .first = 70, .second = 46},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 76, .second = 84},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 76, .second = 86},
    {.amount = -1, .first = 84, .second = 46},
    {.amount = -1, .first = 84, .second = 111},
    {.amount = -1, .first = 76, .second = 89},
    {.amount = -1, .first = 84, .second = 114},
    {.amount = -1, .first = 84, .second = 115},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 117},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 84, .second = 119},
    {.amount = -1, .first = 86, .second = 46},
    {.amount = -1, .first = 84, .second = 121},
    {.amount = -1, .first = 84, .second = 58},
    {.amount = -1, .first = 89, .second = 97},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 87, .second = 46},
    {.amount = -1, .first = 89, .second = 101},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 89, .second = 45},
    {.amount = -1, .first = 89, .second = 46},
    {.amount = -1, .first = 89, .second = 111},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 89, .second = 117},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 89, .second = 58},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 45, .second = 89},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
    {.amount = -1, .first = 80, .second = 46},
    {.amount = 0, .first = 0, .second = 0},
};


struct FontSymbol gDejaVuSansSymbols[] = {
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 79, .y = 9,
        .width = 1, .height = 1,
        .xoffset = 0, .yoffset = 10,
        .xadvance = 4,
    },
    {
        .x = 89, .y = 2,
        .width = 3, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 4,
    },
    {
        .x = 10, .y = 2,
        .width = 4, .height = 4,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 5,
    },
    {
        .x = 41, .y = 40,
        .width = 10, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 9,
    },
    {
        .x = 35, .y = 51,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 96, .y = 40,
        .width = 11, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 10,
    },
    {
        .x = 52, .y = 40,
        .width = 10, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 9,
    },
    {
        .x = 7, .y = 2,
        .width = 2, .height = 4,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 3,
    },
    {
        .x = 11, .y = 50,
        .width = 5, .height = 10,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 4,
    },
    {
        .x = 17, .y = 50,
        .width = 5, .height = 10,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 4,
    },
    {
        .x = 25, .y = 2,
        .width = 7, .height = 5,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 6,
    },
    {
        .x = 55, .y = 30,
        .width = 9, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 9,
    },
    {
        .x = 6, .y = 57,
        .width = 4, .height = 3,
        .xoffset = 0, .yoffset = 9,
        .xadvance = 4,
    },
    {
        .x = 33, .y = 6,
        .width = 5, .height = 2,
        .xoffset = 0, .yoffset = 7,
        .xadvance = 4,
    },
    {
        .x = 101, .y = 8,
        .width = 3, .height = 2,
        .xoffset = 1, .yoffset = 9,
        .xadvance = 4,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 17, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 118, .y = 2,
        .width = 6, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 47, .y = 12,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 26, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 35, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 44, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 53, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 62, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 71, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 80, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 97, .y = 4,
        .width = 3, .height = 6,
        .xoffset = 1, .yoffset = 5,
        .xadvance = 4,
    },
    {
        .x = 1, .y = 53,
        .width = 4, .height = 7,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 4,
    },
    {
        .x = 59, .y = 3,
        .width = 9, .height = 6,
        .xoffset = 1, .yoffset = 4,
        .xadvance = 9,
    },
    {
        .x = 39, .y = 4,
        .width = 9, .height = 4,
        .xoffset = 1, .yoffset = 5,
        .xadvance = 9,
    },
    {
        .x = 69, .y = 3,
        .width = 9, .height = 6,
        .xoffset = 1, .yoffset = 4,
        .xadvance = 9,
    },
    {
        .x = 55, .y = 12,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 6,
    },
    {
        .x = 113, .y = 51,
        .width = 12, .height = 10,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 11,
    },
    {
        .x = 65, .y = 30,
        .width = 9, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 63, .y = 12,
        .width = 7, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 75, .y = 30,
        .width = 9, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 89, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 71, .y = 12,
        .width = 7, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 1, .y = 12,
        .width = 6, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 6,
    },
    {
        .x = 85, .y = 30,
        .width = 9, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 9,
    },
    {
        .x = 98, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 93, .y = 2,
        .width = 3, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 3,
    },
    {
        .x = 65, .y = 51,
        .width = 5, .height = 10,
        .xoffset = -1, .yoffset = 3,
        .xadvance = 3,
    },
    {
        .x = 107, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 79, .y = 12,
        .width = 7, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 6,
    },
    {
        .x = 95, .y = 30,
        .width = 9, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 9,
    },
    {
        .x = 116, .y = 21,
        .width = 8, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 63, .y = 40,
        .width = 10, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 9,
    },
    {
        .x = 87, .y = 12,
        .width = 7, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 44, .y = 51,
        .width = 10, .height = 9,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 9,
    },
    {
        .x = 1, .y = 30,
        .width = 8, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 10, .y = 30,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 105, .y = 30,
        .width = 9, .height = 8,
        .xoffset = -1, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 115, .y = 30,
        .width = 9, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 1, .y = 40,
        .width = 9, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 108, .y = 40,
        .width = 12, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 11,
    },
    {
        .x = 11, .y = 40,
        .width = 9, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 21, .y = 40,
        .width = 9, .height = 8,
        .xoffset = -1, .yoffset = 3,
        .xadvance = 7,
    },
    {
        .x = 31, .y = 40,
        .width = 9, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 8,
    },
    {
        .x = 23, .y = 50,
        .width = 5, .height = 10,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 4,
    },
    {
        .x = 29, .y = 51,
        .width = 5, .height = 9,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 4,
    },
    {
        .x = 121, .y = 39,
        .width = 4, .height = 10,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 4,
    },
    {
        .x = 15, .y = 2,
        .width = 9, .height = 4,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 9,
    },
    {
        .x = 104, .y = 59,
        .width = 8, .height = 2,
        .xoffset = -1, .yoffset = 11,
        .xadvance = 6,
    },
    {
        .x = 1, .y = 1,
        .width = 5, .height = 3,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 6,
    },
    {
        .x = 95, .y = 14,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 15, .y = 11,
        .width = 7, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 103, .y = 14,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 6,
    },
    {
        .x = 23, .y = 11,
        .width = 7, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 19, .y = 32,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 111, .y = 1,
        .width = 6, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 4,
    },
    {
        .x = 71, .y = 53,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 31, .y = 11,
        .width = 7, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
    },
    {
        .x = 81, .y = 1,
        .width = 3, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 3,
    },
    {
        .x = 59, .y = 50,
        .width = 5, .height = 11,
        .xoffset = -1, .yoffset = 2,
        .xadvance = 3,
    },
    {
        .x = 39, .y = 11,
        .width = 7, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 6,
    },
    {
        .x = 85, .y = 1,
        .width = 3, .height = 9,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 3,
    },
    {
        .x = 74, .y = 42,
        .width = 10, .height = 6,
        .xoffset = 1, .yoffset = 5,
        .xadvance = 11,
    },
    {
        .x = 111, .y = 14,
        .width = 7, .height = 6,
        .xoffset = 1, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 28, .y = 32,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 79, .y = 53,
        .width = 7, .height = 8,
        .xoffset = 1, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 87, .y = 53,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 105, .y = 4,
        .width = 5, .height = 6,
        .xoffset = 1, .yoffset = 5,
        .xadvance = 5,
    },
    {
        .x = 119, .y = 14,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 6,
    },
    {
        .x = 8, .y = 12,
        .width = 6, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 4,
    },
    {
        .x = 1, .y = 23,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 37, .y = 32,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 85, .y = 42,
        .width = 10, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 9,
    },
    {
        .x = 46, .y = 32,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 95, .y = 53,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 7,
    },
    {
        .x = 9, .y = 23,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 5,
        .xadvance = 6,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 55, .y = 50,
        .width = 3, .height = 11,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 4,
    },
    {
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
    },
    {
        .x = 49, .y = 4,
        .width = 9, .height = 4,
        .xoffset = 1, .yoffset = 5,
        .xadvance = 9,
    },
};

struct Font gDejaVuSansFont = {
    .kerning = &gDejaVuSansKerning[0],
    .symbols = &gDejaVuSansSymbols[0],
    .base = 10,
    .charHeight = 12,
    .symbolCount = 127,
    .kerningMultiplier = 5,
    .kerningMask = 0x3f,
    .maxCollisions = 1,
};

