

#include "font.h"

struct FontKerning gLiberationMonoKerning[] = {
    {.amount = 0, .first = 0, .second = 0},
    {.amount = 0, .first = 0, .second = 0},
};


struct FontSymbol gLiberationMonoSymbols[] = {
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 32,
        .x = 71, .y = 10,
        .width = 1, .height = 0,
        .xoffset = 0, .yoffset = 9,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 33,
        .x = 73, .y = 3,
        .width = 3, .height = 7,
        .xoffset = 2, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 34,
        .x = 10, .y = 2,
        .width = 6, .height = 3,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 35,
        .x = 1, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 36,
        .x = 109, .y = 37,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 37,
        .x = 10, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 38,
        .x = 19, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 39,
        .x = 6, .y = 2,
        .width = 3, .height = 3,
        .xoffset = 2, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 40,
        .x = 1, .y = 48,
        .width = 5, .height = 10,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 41,
        .x = 7, .y = 48,
        .width = 5, .height = 10,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 42,
        .x = 23, .y = 2,
        .width = 6, .height = 5,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 43,
        .x = 63, .y = 12,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 44,
        .x = 122, .y = 43,
        .width = 4, .height = 4,
        .xoffset = 1, .yoffset = 7,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 45,
        .x = 17, .y = 6,
        .width = 5, .height = 1,
        .xoffset = 1, .yoffset = 5,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 46,
        .x = 81, .y = 8,
        .width = 3, .height = 2,
        .xoffset = 2, .yoffset = 7,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 47,
        .x = 15, .y = 11,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 48,
        .x = 71, .y = 12,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 49,
        .x = 28, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 50,
        .x = 79, .y = 12,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 51,
        .x = 87, .y = 12,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 52,
        .x = 37, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 53,
        .x = 95, .y = 12,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 54,
        .x = 103, .y = 12,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 55,
        .x = 111, .y = 12,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 56,
        .x = 119, .y = 12,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 57,
        .x = 1, .y = 21,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 58,
        .x = 77, .y = 4,
        .width = 3, .height = 6,
        .xoffset = 2, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 59,
        .x = 25, .y = 50,
        .width = 5, .height = 8,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 60,
        .x = 55, .y = 4,
        .width = 7, .height = 5,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 61,
        .x = 47, .y = 5,
        .width = 7, .height = 3,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 62,
        .x = 63, .y = 4,
        .width = 7, .height = 5,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 63,
        .x = 9, .y = 21,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 64,
        .x = 77, .y = 48,
        .width = 8, .height = 10,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 65,
        .x = 46, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 66,
        .x = 55, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 67,
        .x = 64, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 68,
        .x = 73, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 69,
        .x = 82, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 70,
        .x = 106, .y = 3,
        .width = 6, .height = 7,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 71,
        .x = 17, .y = 21,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 72,
        .x = 25, .y = 21,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 73,
        .x = 113, .y = 3,
        .width = 6, .height = 7,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 74,
        .x = 33, .y = 21,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 75,
        .x = 91, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 76,
        .x = 120, .y = 3,
        .width = 6, .height = 7,
        .xoffset = 1, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 77,
        .x = 41, .y = 21,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 78,
        .x = 49, .y = 21,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 79,
        .x = 100, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 80,
        .x = 109, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 81,
        .x = 86, .y = 49,
        .width = 8, .height = 9,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 82,
        .x = 118, .y = 29,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 83,
        .x = 1, .y = 38,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 84,
        .x = 10, .y = 38,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 85,
        .x = 57, .y = 21,
        .width = 7, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 86,
        .x = 19, .y = 38,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 87,
        .x = 28, .y = 38,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 88,
        .x = 37, .y = 38,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 89,
        .x = 46, .y = 38,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 90,
        .x = 55, .y = 38,
        .width = 8, .height = 7,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 91,
        .x = 13, .y = 48,
        .width = 5, .height = 10,
        .xoffset = 2, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 92,
        .x = 23, .y = 11,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 93,
        .x = 19, .y = 48,
        .width = 5, .height = 10,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 94,
        .x = 39, .y = 3,
        .width = 7, .height = 5,
        .xoffset = 0, .yoffset = 2,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 95,
        .x = 104, .y = 57,
        .width = 9, .height = 1,
        .xoffset = -1, .yoffset = 10,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 96,
        .x = 1, .y = 1,
        .width = 4, .height = 2,
        .xoffset = 2, .yoffset = 0,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 97,
        .x = 64, .y = 39,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 98,
        .x = 31, .y = 11,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 99,
        .x = 65, .y = 22,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 100,
        .x = 39, .y = 11,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 101,
        .x = 73, .y = 22,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 102,
        .x = 47, .y = 11,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 103,
        .x = 53, .y = 50,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 104,
        .x = 85, .y = 2,
        .width = 6, .height = 8,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 105,
        .x = 113, .y = 20,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 106,
        .x = 31, .y = 48,
        .width = 6, .height = 10,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 107,
        .x = 55, .y = 11,
        .width = 7, .height = 8,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 108,
        .x = 92, .y = 2,
        .width = 6, .height = 8,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 109,
        .x = 73, .y = 39,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 110,
        .x = 81, .y = 22,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 111,
        .x = 89, .y = 22,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 112,
        .x = 61, .y = 50,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 113,
        .x = 69, .y = 50,
        .width = 7, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 114,
        .x = 1, .y = 13,
        .width = 6, .height = 6,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 115,
        .x = 97, .y = 22,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 116,
        .x = 99, .y = 2,
        .width = 6, .height = 8,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 117,
        .x = 8, .y = 13,
        .width = 6, .height = 6,
        .xoffset = 1, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 118,
        .x = 82, .y = 39,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 119,
        .x = 91, .y = 39,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 120,
        .x = 100, .y = 39,
        .width = 8, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 121,
        .x = 95, .y = 50,
        .width = 8, .height = 8,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 122,
        .x = 105, .y = 22,
        .width = 7, .height = 6,
        .xoffset = 0, .yoffset = 3,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 123,
        .x = 38, .y = 48,
        .width = 6, .height = 10,
        .xoffset = 1, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 124,
        .x = 118, .y = 37,
        .width = 3, .height = 10,
        .xoffset = 2, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 125,
        .x = 45, .y = 48,
        .width = 7, .height = 10,
        .xoffset = 0, .yoffset = 1,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 126,
        .x = 30, .y = 5,
        .width = 8, .height = 2,
        .xoffset = 0, .yoffset = 4,
        .xadvance = 7,
        .textureIndex = 0,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
    {
        .id = 0,
        .x = 0, .y = 0,
        .width = 0, .height = 0,
        .xoffset = 0, .yoffset = 0,
        .xadvance = 0,
        .textureIndex = -1,
    },
};

struct Font gLiberationMonoFont = {
    .kerning = &gLiberationMonoKerning[0],
    .symbols = &gLiberationMonoSymbols[0],
    .base = 9,
    .charHeight = 12,
    .symbolMultiplier = 1,
    .symbolMask = 0xff,
    .symbolMaxCollisions = 0,
    .kerningMultiplier = 1,
    .kerningMask = 0x1,
    .kerningMaxCollisions = 0,
};

