
#ifndef __DEFS_H__
#define __DEFS_H__

#define	STACKSIZEBYTES	0x2000

#define MAX_FRAME_BUFFER_MESGS	8

#define IDLE_THREAD_ID       1
#define GAME_THREAD_ID       2
#define CONTROLLER_THREAD_ID 3
#define AUDIO_THREAD_ID      4

#define INIT_PRIORITY		10
#define GAME_PRIORITY		10
#define CONTROLLER_PRIORITY 11
#define AUDIO_PRIORITY		12
#define SCHEDULER_PRIORITY	13
#define RSP_PROFILE_PRIORITY 14
#define NUM_FIELDS      1

#define LEVEL_SEGMENT 2
#define DYNAMIC_MODEL_SEGMENT 3

#ifndef SCENE_SCALE
#define SCENE_SCALE 128
#endif

#define MAX_DYNAMIC_COLLISION   64

#define MAX_RENDER_COUNT        256

#endif
